# Regular NumPy Arrays

A specialized class is numpy.ndarray, which has been built with the specific goal of
handling n-dimensional arrays both conveniently and efficiently

In [ ]:
import numpy as np

In [2]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])

array([0. , 0.5, 1. , 1.5, 2. ])

In [3]:
a

array([0. , 0.5, 1. , 1.5, 2. ])

# indexing as with list objects in 1 dimension

In [4]:
a[:2] 

array([0. , 0.5])

In [5]:
a.sum() # sum of all elements

5.0

In [6]:
a.std() # standard deviation

0.7071067811865476

In [7]:
a.cumsum() # running cumulative sum

array([0. , 0.5, 1.5, 3. , 5. ])

Another major feature is the (vectorized) mathematical operations defined on ndarray
objects:

In [8]:
a*2

array([0., 1., 2., 3., 4.])

In [9]:
a**2

array([0.  , 0.25, 1.  , 2.25, 4.  ])

In [10]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

The transition to more than one dimension is seamless, and all features presented so far
carry over to the more general cases.

In [11]:
b = np.array([a, a * 2])

In [12]:
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [13]:
b[0] # first row

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
b[0, 2] # third element of first row

1.0

In [15]:
b.sum()

15.0

In [16]:
b.sum(axis=0)
# sum along axis 0, i.e. column-wise sum

array([0. , 1.5, 3. , 4.5, 6. ])

In [17]:
b.sum(axis=1)
# sum along axis 1, i.e. row-wise sum

array([ 5., 10.])

There are a number of ways to initialize (instantiate) a numpy.ndarray object. one would maybe like to have the numpy.ndarray objects instantiated first to populate them later with results generated during the execution of
code.

In [20]:
c = np.zeros((2, 3, 4), dtype='i', order='C')  # also: np.ones()

In [21]:
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [23]:
d = np.ones_like(c, dtype='f', order='C') # also: np.zeros_like()

In [24]:
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

###Structured Arrays

In [26]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])

In [27]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [28]:
s = np.array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))], dtype=dt)

In [29]:
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [31]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [33]:
s['Height'].mean()

1.7750001

Having selected a specific row and record, respectively, the resulting objects mainly
behave like dict objects, where one can retrieve values via keys:

In [34]:
s[1]['Age']

53

## Vectorization of Code

Basic Vectorization

In [37]:
r = np.random.standard_normal((4, 3))
s = np.random.standard_normal((4, 3))

In [38]:
r+s

array([[-1.91981736,  0.7255817 ,  0.43858727],
       [-1.20488131,  0.82366356, -0.7244405 ],
       [ 0.02401409,  1.47294517, -0.67714221],
       [-0.97678308,  2.37953248,  1.21547535]])

NumPy also supports what is called broadcasting. This allows us to combine objects of different shape within a single operation

In [39]:
2 * r + 3

array([[ 0.83431017,  4.82687076,  3.99854964],
       [ 1.34198417,  3.28444019,  2.63696932],
       [ 3.5249047 ,  5.00414976,  1.38965184],
       [-0.20343982,  5.33942598,  6.58858005]])

In this case, the r object is multiplied by 2 element-wise and then 3 is added element-wise
— the 3 is broadcasted or stretched to the shape of the r object. It works with differently
shaped arrays as well, up to a certain point:

In [42]:
s = np.random.standard_normal(3)
s

array([-0.05189928, -0.04301694, -1.13058829])

In [43]:
r+s

array([[-1.1347442 ,  0.87041844, -0.63131347],
       [-0.8809072 ,  0.09920316, -1.31210363],
       [ 0.21055307,  0.95905794, -1.93576237],
       [-1.65361919,  1.12669605,  0.66370173]])

This broadcasts the one-dimensional array of size 3 to a shape of (4, 3). The same does not
work, for example, with a one-dimensional array of size 4:


In [44]:
 s = np.random.standard_normal(4)

In [46]:
r + s #ValueError: operands could not be broadcast together with shapes (4,3) (4,)

However, transposing the r object makes the operation work again. In the following code,
the transpose method transforms the ndarray object with shape (4, 3) into an object of
the same type with shape (3, 4):

In [47]:
r.transpose() + s

array([[-0.93530454, -1.57442857,  0.22750963, -3.12692068],
       [ 1.06097575, -0.60320056,  0.96713216, -0.35548778],
       [ 0.64681519, -0.926936  , -0.8401168 ,  0.26908925]])

In [48]:
np.shape(r.T)

(3, 4)

In [49]:
def f(x):
    return 3 * x + 5

In [50]:
f(0.5) # float object

6.5

In [51]:
f(r) # NumPy array

array([[ 1.75146525,  7.74030614,  6.49782446],
       [ 2.51297626,  5.42666029,  4.45545397],
       [ 5.78735705,  8.00622464,  2.58447776],
       [ 0.19484028,  8.50913897, 10.38287008]])

In [52]:
import math
math.sin(r) # error

TypeError: only size-1 arrays can be converted to Python scalars

In [53]:
np.sin(r) # array as input

array([[-0.88329513,  0.79160753,  0.47878901],
       [-0.73726147,  0.14174114, -0.18052023],
       [ 0.2594497 ,  0.84259023, -0.72095129],
       [-0.9995219 ,  0.92063858,  0.97512907]])

In [54]:
np.sin(np.pi) # float as input

1.2246467991473532e-16

In [56]:
x = np.random.standard_normal((5, 10000000))
y = 2 * x + 3 # linear equation y = a * x + b
C = np.array((x, y), order='C')
F = np.array((x, y), order='F')
x = 0.0; y = 0.0 # memory cleanup

In [57]:
C[:2].round(2)

array([[[ 1.4 , -1.4 , -1.16, ...,  0.71,  0.22, -0.96],
        [ 1.46,  0.13,  1.5 , ...,  0.72, -0.37,  0.18],
        [-0.07, -1.98,  0.5 , ...,  0.29,  0.43, -0.96],
        [ 0.33, -0.27,  1.47, ...,  1.37, -0.8 ,  0.22],
        [-1.07,  0.23, -1.36, ..., -1.06, -0.27, -1.49]],

       [[ 5.79,  0.21,  0.68, ...,  4.42,  3.45,  1.08],
        [ 5.93,  3.27,  6.01, ...,  4.44,  2.27,  3.37],
        [ 2.85, -0.97,  4.  , ...,  3.58,  3.86,  1.08],
        [ 3.66,  2.46,  5.94, ...,  5.73,  1.39,  3.44],
        [ 0.87,  3.46,  0.27, ...,  0.89,  2.45,  0.01]]])

To estimate the future value at the end of year two with a 10% annual interest rate,

In [58]:
import scipy as sp

In [59]:
sp.fv(0.1,2,0,100)

-121.00000000000001

sp.fv(rate,nper,pmt,pv=0,when='end')

In [61]:
help(sp.fv)

If we plan to have $234 at the end of year five and the interest rate is 1.45% per year, how
much we have to deposit today?

In [62]:
sp.pv(0.0145,5,0,234)

-217.74871488824184